BigGAN_bs256x8:
  dataset: 'I128_hdf5'
  data_root: "~/.keras/BigGAN-PyTorch-1/ILSVRC128.hdf5"
  inception_file: "~/.keras/BigGAN-PyTorch-1/I128_inception_moments.npz"
#  which_train_fn: 'dummy'
  which_train_fn: 'GAN'
  parallel: true
  shuffle: true
  num_workers: 8
  batch_size: 2
#  batch_size: 256
  load_in_mem: false
#  load_in_mem: true
  num_G_accumulations: 8
  num_D_accumulations: 8
  num_D_steps: 1
  G_lr: 0.0001
  D_lr: 0.0004
  D_B2: 0.999
  G_B2: 0.999
  G_attn: '64'
  D_attn: '64'
  G_nl: 'inplace_relu'
  D_nl: 'inplace_relu'
  SN_eps: 1.e-06
  BN_eps: 1.e-05
  adam_eps: 1.e-06
  G_ortho: 0.0
  G_shared: true
  G_init: 'ortho'
  D_init: 'ortho'
  hier: true
  dim_z: 120
  shared_dim: 128
  G_eval_mode: true
  G_ch: 96
  D_ch: 96
  ema: true
  use_ema: true
  ema_start: 20000
  test_every: 2000
#  test_every: 2000
  save_every: 1000
  num_best_copies: 5
  num_save_copies: 2
  seed: 0
  use_multiepoch_sampler: true
  experiment_name: 'exp'

BigGAN_bs256x8_wgan_gpreal:
  dataset: 'I128_hdf5'
  data_root: "~/.keras/BigGAN-PyTorch-1/ILSVRC128.hdf5"
  inception_file: "~/.keras/BigGAN-PyTorch-1/I128_inception_moments.npz"
#  which_train_fn: 'dummy'
  which_train_fn: 'wgan_gpreal'
  parallel: true
  shuffle: true
  num_workers: 8
  batch_size: 32
#  batch_size: 256
  load_in_mem: false
#  load_in_mem: true
  num_G_accumulations: 8
  num_D_accumulations: 8
  num_D_steps: 1
  G_lr: 0.0001
  D_lr: 0.0004
  D_B2: 0.999
  G_B2: 0.999
  G_attn: '64'
  D_attn: '64'
  G_nl: 'inplace_relu'
  D_nl: 'inplace_relu'
  SN_eps: 1.e-06
  BN_eps: 1.e-05
  adam_eps: 1.e-06
  G_ortho: 0.0
  G_shared: true
  G_init: 'ortho'
  D_init: 'ortho'
  hier: true
  dim_z: 120
  shared_dim: 128
  G_eval_mode: true
  G_ch: 96
  D_ch: 96
  ema: true
  use_ema: true
  ema_start: 20000
  test_every: 2000
#  test_every: 2000
  save_every: 1000
  num_best_copies: 5
  num_save_copies: 2
  seed: 0
  use_multiepoch_sampler: true
  experiment_name: 'exp'
  train_fns_c:
    use_bound: false
    adv_train: false

BigGAN_bs256x8_wgan_gpreal_adv:
  dataset: 'I128_hdf5'
  data_root: "~/.keras/BigGAN-PyTorch-1/ILSVRC128.hdf5"
  inception_file: "~/.keras/BigGAN-PyTorch-1/I128_inception_moments.npz"
#  which_train_fn: 'dummy'
  which_train_fn: 'wgan_gpreal'
  parallel: true
  shuffle: true
  num_workers: 8
  batch_size: 16
#  batch_size: 256
  load_in_mem: false
#  load_in_mem: true
  num_G_accumulations: 1
  num_D_accumulations: 1
#  num_G_accumulations: 8
#  num_D_accumulations: 8
  num_D_steps: 1
  G_lr: 0.0001
  D_lr: 0.0004
  D_B2: 0.999
  G_B2: 0.999
  G_attn: '64'
  D_attn: '64'
  G_nl: 'inplace_relu'
  D_nl: 'inplace_relu'
  SN_eps: 1.e-06
  BN_eps: 1.e-05
  adam_eps: 1.e-06
  G_ortho: 0.0
  G_shared: true
  G_init: 'ortho'
  D_init: 'ortho'
  hier: true
  dim_z: 120
  shared_dim: 128
  G_eval_mode: true
  G_ch: 96
  D_ch: 96
  ema: true
  use_ema: true
  ema_start: 20000
  test_every: 2000
#  test_every: 2000
  save_every: 1000
  num_best_copies: 5
  num_save_copies: 2
  seed: 0
  use_multiepoch_sampler: true
  experiment_name: 'exp'
  train_fns_c:
    use_bound: false
    adv_train: true


BigGAN_bs256x8_wbgan_gpreal:
  dataset: 'I128_hdf5'
  data_root: "~/.keras/BigGAN-PyTorch-1/ILSVRC128.hdf5"
  inception_file: "~/.keras/BigGAN-PyTorch-1/I128_inception_moments.npz"
#  which_train_fn: 'dummy'
  which_train_fn: 'wbgan_gpreal'
  parallel: true
  shuffle: true
  num_workers: 8
  batch_size: 32
#  batch_size: 256
  load_in_mem: false
#  load_in_mem: true
  num_G_accumulations: 8
  num_D_accumulations: 8
  num_D_steps: 1
  G_lr: 0.0001
  D_lr: 0.0004
  D_B2: 0.999
  G_B2: 0.999
  G_attn: '64'
  D_attn: '64'
  G_nl: 'inplace_relu'
  D_nl: 'inplace_relu'
  SN_eps: 1.e-06
  BN_eps: 1.e-05
  adam_eps: 1.e-06
  G_ortho: 0.0
  G_shared: true
  G_init: 'ortho'
  D_init: 'ortho'
  hier: true
  dim_z: 120
  shared_dim: 128
  G_eval_mode: true
  G_ch: 96
  D_ch: 96
  ema: true
  use_ema: true
  ema_start: 20000
  test_every: 2000
#  test_every: 2000
  save_every: 1000
  num_best_copies: 5
  num_save_copies: 2
  seed: 0
  use_multiepoch_sampler: true
  experiment_name: 'exp'
  bound: 100








